### ISSUE TITLE
Are the extra bits for litlen calculated correctly for litlen symbol 284?

### ISSUE THREAD

**Issue by esoha-nvidia** [madler/infgen#10]
https://github.com/madler/infgen/blob/98835d9ee6910801adbd4484d1e93b6768e6a8b5/infgen.c#L1060

RFc 1951 has a few bugs in it including this one:

```
                 Extra               Extra               Extra
            Code Bits Length(s) Code Bits Lengths   Code Bits Length(s)
            ---- ---- ------     ---- ---- -------   ---- ---- -------
             257   0     3       267   1   15,16     277   4   67-82
             258   0     4       268   1   17,18     278   4   83-98
             259   0     5       269   2   19-22     279   4   99-114
             260   0     6       270   2   23-26     280   4  115-130
             261   0     7       271   2   27-30     281   5  131-162
             262   0     8       272   2   31-34     282   5  163-194
             263   0     9       273   3   35-42     283   5  195-226
             264   0    10       274   3   43-50     284   5  227-257
             265   1  11,12      275   3   51-58     285   0    258
             266   1  13,14      276   3   59-66
```

We can see that after symbol 284, there are ought to be 5 extra bits.  However, the range for that one is 227-257, which, unlike all the other ranges, is not a power of 2 in size.  We can see that symbol 284, followed by five bits of 1, is invalid?

`infgen` treats it as if the length will be 258.  Should it be an error?  Has this ever been encountered?

I've found bugs in RFC 1951 before but this is the first time that I noticed this one.  I'm assuming that the RFC author simply made a mistake.  :shrug:

**Comment by madler** [comment]
This is neither a bug nor a mistake. The RFC is correct. The codes support two different ways to code a length of 258. The longer way, code 284 followed by 11111b, should not be used and is not permitted by the specification, per the table you quote. Code 285 with no extra bits must be used to code a length of 285.

infgen as well as zlib are permissive in this regard, and will accept both representations of length 258. zlib's deflate will never produce the invalid representation.

What are these other bugs you say you have found in RFC 1951?

**Comment by esoha-nvidia** [comment]
How come, below, it says that you can only have a maximum of 286 litlen symbols yet it also says that you can have 32 dist codes?
```
        We can now define the format of the block:

               5 Bits: HLIT, # of Literal/Length codes - 257 (257 - 286)
               5 Bits: HDIST, # of Distance codes - 1        (1 - 32)
               4 Bits: HCLEN, # of Code Length codes - 4     (4 - 19)
```

Even though the HLIT has five bits, which could potentially be up to 31, we see that the range for the number of litlen codes cannot be `257+31=288` because codes 286 and 287 are not valid.  We can see it in the table:

```
                 Extra               Extra               Extra
            Code Bits Length(s) Code Bits Lengths   Code Bits Length(s)
            ---- ---- ------     ---- ---- -------   ---- ---- -------
             257   0     3       267   1   15,16     277   4   67-82
             258   0     4       268   1   17,18     278   4   83-98
             259   0     5       269   2   19-22     279   4   99-114
             260   0     6       270   2   23-26     280   4  115-130
             261   0     7       271   2   27-30     281   5  131-162
             262   0     8       272   2   31-34     282   5  163-194
             263   0     9       273   3   35-42     283   5  195-226
             264   0    10       274   3   43-50     284   5  227-257
             265   1  11,12      275   3   51-58     285   0    258
             266   1  13,14      276   3   59-66
```

That's why it says range `257-286` and not `257-288`.

Dist shows that the range is `1-32`, so I would expect that the dist table has symbols 0 through 31.  However:

```
                  Extra           Extra               Extra
             Code Bits Dist  Code Bits   Dist     Code Bits Distance
             ---- ---- ----  ---- ----  ------    ---- ---- --------
               0   0    1     10   4     33-48    20    9   1025-1536
               1   0    2     11   4     49-64    21    9   1537-2048
               2   0    3     12   5     65-96    22   10   2049-3072
               3   0    4     13   5     97-128   23   10   3073-4096
               4   1   5,6    14   6    129-192   24   11   4097-6144
               5   1   7,8    15   6    193-256   25   11   6145-8192
               6   2   9-12   16   7    257-384   26   12  8193-12288
               7   2  13-16   17   7    385-512   27   12 12289-16384
               8   3  17-24   18   8    513-768   28   13 16385-24576
               9   3  25-32   19   8   769-1024   29   13 24577-32768
```

Only 30 symbols.  The RFC seems inconsistent here.

BTW, any idea why someone would decide to make make code 284 followed by five 1s not be used?  Seems like it would have been easier allow for that longer code and just eliminate the length 285 entirely.  Is 285 a very common copy length or something?

**Comment by madler** [comment]
Yes, it should say `(1 - 30)` for HDIST.

It certainly makes sense to have the longest match length be a code with _no_ extra bits. Then a long sequence of the same byte, e.g. a long string of zeros, can be coded with just two bits for each such match, one for the distance code and one for the length code. That results in the maximum possible compression ratio of the deflate format, which is 258 bytes out for 2 bits in, or a ratio of 1032:1. If instead the longest length took six bits, the maximum compression ratio would be about 295:1.

The next question might then be: why not make code 285 represent a length of 259 instead of 258, which can already be represented by code 284? Here I can only guess (the author of deflate passed away in 2000), where my guess is that the allowed match lengths 3..258 can be represented in a single byte by subtracting three. There may have been some benefit to that representation in the original PKZip deflate code written in 8086 assembler.
