### ISSUE TITLE
I CAN'T COMPILE 😭😭😭

### ISSUE THREAD

**Issue by Github3010** [madler/infgen#11]
Hello, i was trying to compile this, but bad news happened. An error occured like below:

C:\Users\516da\AppData\Local\Temp\cc4Stu7f.o:infgen.c:(.text+0x55f): undefined reference to `crc32'
C:\Users\516da\AppData\Local\Temp\cc4Stu7f.o:infgen.c:(.text+0x573): undefined reference to `crc32'
C:\Users\516da\AppData\Local\Temp\cc4Stu7f.o:infgen.c:(.text+0x62f): undefined reference to `crc32'
C:\Users\516da\AppData\Local\Temp\cc4Stu7f.o:infgen.c:(.text+0x3d34): undefined reference to `get_crc_table'
collect2.exe: error: ld returned 1 exit status

How do I fix this?

**Comment by madler** [comment]
You need to link in the zlib library. It looks like you're on Windows, so you should be able to use the nuget package manager in Visual Studio to install the library.

**Comment by Github3010** [comment]
I tried installing, but i get the same error when compiling.

**Comment by Github3010** [comment]
Okay, i tried dotnet in my terminal, but it gives me install errors.
