### ISSUE TITLE
Request to extend to png.

### ISSUE THREAD

**Issue by DavidPynes** [madler/infgen#2]
@madler, can infgen incorporate the png too? 

        else if (head && n != EOF && val == 0x8950) {
            /* png */
            if (wrap)
                fputs("!\n", s.out);
            const unsigned char png_magic[6] = { 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a };
            int i = 0;
            while (i < 6) /* magic png */
                if (NEXT(s.in) != png_magic[i++]) //increment i
                    bail("misinterpreted png");
            while (num != 0x49444154) {
                num = NEXT(s.in);
                if (num == 0x49) {
                    num = (num << 8) + NEXT(s.in);
                    num = (num << 8) + NEXT(s.in);
                    num = (num << 8) + NEXT(s.in);
                }
            ret = NEXT(s.in);
            n = NEXT(s.in);
            val = ((unsigned)ret << 8) + (unsigned)n;   /* magic two bytes */
        }
        ...

**Comment by TPS** [comment]
@madler I just wanted to drop by & say, "Thanks!" for `infgen` & all your contributions to computer & data science.  This utility itself is [helping us work through an RFE even today](https://github.com/shssoichiro/oxipng/issues/420#issuecomment-1635452987). 🙇🏾‍♂️

I see the [commit](https://github.com/madler/infgen/commit/6f4eddbccb8957516389c7c87f1e255e93ef2689) where it got extended to PNG.

**Comment by madler** [comment]
Done.

**Comment by TPS** [comment]
@madler Thanks very much again

**Comment by DavidPynes** [comment]
@madler, thanks for your work creating zlib. That program/codec has inspired and taught me many things beyond code length codes, and non-optimal Huffman trees.
