### ISSUE TITLE
Please may you release under a free (libre) license?

### ISSUE THREAD

**Issue by throwaway1037** [madler/infgen#7]

**Comment by madler** [comment]
It already is.

**Comment by throwaway1037** [comment]
There is no license file, and the license included says "all rights reserved" and "it can be used for personal enlightenment", neither of which indicate free software.

Please may you release under a [recognised free (libre) license](https://gnu.org/licenses/license-list.html)?

**Comment by XlogicX** [comment]
I would like to resoundingly 2nd this request. infgen has been SUPER helpful for me in the past. As I got into the weeds with DEFLATE, there were a few more things I wanted infgen to do, so I modified a local copy to do those things and would love to put it out there, I was just about to now, but got cautious with the copyright. Though it would be a true 'fork,' I don't think the entire user-base would agree to the direction of what would be the flavor I added (so not a pull request).

**Comment by madler** [comment]
Done. https://github.com/madler/infgen/commit/0fdd8d4072910311f05438dbbc4986ffe8fff2be

**Comment by XlogicX** [comment]
Amazing! I appreciate that. I now have a fork at: https://github.com/XlogicX/infgen
I added some corresponding color coding with a final full bitstream output at the end (-c)
I also added a dump of each generated Huffman table (in dynamic mode) (-t). I probably didn't need to create an entire function for that, as the data is there, but I suck at c...
