### ISSUE TITLE
Intermitent failures "i/o error: No such file or directory" when running in docker

### ISSUE THREAD

**Issue by esoha-nvidia** [madler/infgen#9]
```
root@3727bfcccc47:/home/esoha/coding/infgen# ./infgen '-isd' 'medium-sample.log.gz' > /dev/null
infgen error: i/o error: No such file or directory
```

`infgen` will occasionally fail to `fclose` at the end of processing a file if the filename is given as an argument *and* `infgen` is run inside of a docker container.  The failure occurs about half the time.

Processing the same file by piping it in instead of passing the filename as a command line argument causes no failure.  Running without the docker container also never causes this error:

```
root@3727bfcccc47:/home/esoha/coding/infgen# time cat medium-sample.log.gz | ./infgen '-isd' > /dev/null
```

The error is caused during the `fclose` of the input file `s.in`.  The failure occurs whether or not the file to process is in a mounted volume or not.

Seems like a problem with docker.  The solution is to either remove the `fclose` from the code or just pipe the input in.

**Comment by madler** [comment]
How does "No such file or directory" lead you to believe that fclose is failing at the end? That sounds like fopen is failing at the start.

**Comment by esoha-nvidia** [comment]
> How does "No such file or directory" lead you to believe that fclose is failing at the end?

Because when I commented out the `fclose` at the end of the code and recompiled, the problem went away.

Also, if it were the `fopen` that had failed then there would be no output.  However, I compared the output in the failure cases and the regular cases and both of them have the same output.

**Comment by madler** [comment]
Ok. (That's the sort of thing that belongs in the report. You just showed directing the output to /dev/null. Is there any other information you're leaving out?)

Are you recommending that infgen never close the input file?

**Comment by esoha-nvidia** [comment]
(I *did* mention `fclose` in the report!)

The operating system will flush and close the file for you when the program exits.  But `fclose` ought to work!  I think that docker might be doing something silly with file descriptors, like maybe it invalidates them when a file reads `EOF`, even though it shouldn't?  I'm not sure.

You could leave it as is or remove the `fclose`.  Up to you.  For my needs, I'm calling `infgen` from `python` and it's easiest if the program doesn't report an error so I've removed the `fclose` in my fork pf the repo.  It's your project, do as you like!

https://github.com/madler/infgen/compare/master...esoha-nvidia:infgen:master

**Comment by madler** [comment]
I will change it to not close stdin or stdout before exiting. It will just flush stdout.
